---
title: "Lab 10: Distances and the Border Zone"
subtitle: 'Ecosystem Science and Sustainability 330'
author:
  - name: Melissa May
    email: "melmay@colostate.edu"
format: html
execute:
  echo: true
---

# Lab 10: Distances and the Border Zone

## Loading libraries:

```{r}
# Spatial data science
library(tidyverse)
library(sf)
library(units)

# Data
library(AOI)

# Visualization
library(gghighlight)
library(ggrepel)
library(knitr)
```

## Question 1

### 1.1: Define a Projection

```{r}
eqdc <- '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'
```

### 1.2: Get USA State Boundaries

```{r}
usa_states <- aoi_get(state = "conus")

st_crs(usa_states)

usa_states_eqdc <- st_transform(usa_states, crs = eqdc)

st_crs(usa_states_eqdc)
```

### 1.3: Get Country Boundaries for Mexico, the United States of America, and Canada

```{r}
na_countries <- aoi_get(country = c("MX", "CA", "USA"))

st_crs(na_countries)

na_countries_eqdc <- st_transform(na_countries, crs = eqdc)

st_crs(na_countries_eqdc)
```

### 1.4: Get City Locations from the CSV File

```{r}
cities_df <- read_csv("data/uscities.csv")

glimpse(cities_df)
```

```{r}
cities_sf <- st_as_sf(
  cities_df,
  coords = c("lng", "lat"),
  crs = 4326, # WGS84
  remove = FALSE
)

cities_eqdc <- st_transform(cities_sf, crs = eqdc)
```

```{r}
cities_eqdc <- cities_eqdc %>%
  filter(!state_id %in% c("AK", "HI", "PR", "VI", "GU", "MP", "AS"))
```

## Question 2

### 2.1: Distance to USA Border

```{r}
usa_union <- st_union(usa_states_eqdc)

usa_border <- st_cast(usa_union, "MULTILINESTRING")

cities_sf <- cities_sf %>%
  mutate(dist_usa_border_km = as.numeric(st_distance(geometry, usa_border)) / 1000)

flextable(
  cities_sf %>%
    st_drop_geometry() %>%
    select(city, state, dist_usa_border_km) %>%
    arrange(desc(dist_usa_border_km)) %>%
    slice_head(n = 5)
)
```

### 2.2: Distance to States

### 2.3: Distance to Mexico

### 2.4: Distance to Canada